config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  get "movies" => "movies#index"
  get "movies/:id" => "movies#show", as: "movie"
  get "movies/:id/edit" => "movies#edit", as: "edit_movie"
  patch "movies/:id" => "movies#update"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  def flop?
    total_gross.blank? || total_gross < 225_000_000
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
  def show
    @movie = Movie.find(params[:id])
  end
  def edit
    @movie = Movie.find(params[:id])
  end
  def update
    @movie = Movie.find(params[:id])

    movie_params =
      params.require(:movie).
        permit(:title, :description, :rating, :released_on, :total_gross)

    @movie.update(movie_params)

    redirect_to @movie
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def total_gross(movie)
    if movie.flop?
      "Flop!"
    else
    number_to_currency(movie.total_gross, precision: 0)
    end
  end
def release_year(movie)
  movie.released_on.strftime("%Y")
end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
  <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul>
      <li>
        <%= link_to("All Movies", movies_path) %>
      </li>
    </ul>
  </nav>
</header>
    <div class="content">
      <%= yield %>
    </div>

  <footer>
    <p>
      Copyright &copy; <%= Time.now.year %>
      <%= link_to "Project Github Repo", "https://github.com/Chrisd3r/flix" %>
    </p>
  </footer>

  </body>
</html>

app/views/movies/edit.html.erb
<%= form_with(model: @movie) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 7 %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <%= f.label :released_on %>
  <%= f.date_field :released_on %>

  <%= f.label :total_gross %>
  <%= f.number_field :total_gross %>

  <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
  <section class="movie">
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie %>
      </h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
    </div>
  </section>
  <section class="admin">
  <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
</section>
<% end %>

app/views/movies/show.html.erb
<section class="movie-details">
  <div class="details">
    <h1><%= @movie.title %></h1>
    <h2>
      <%= release_year(@movie) %> &bull; <%= @movie.rating %>
    </h2>
    <p>
      <%= @movie.description %>
    </p>
    <table>
      <tr>
        <th>Total Gross:</th>
        <td><%= total_gross(@movie) %></td>
      </tr>
    </table>
  </div>
</section>